#!/bin/bash 
if [ "$1" == "neutron" ]; then
    echo "neutron | 1:2014.1-0ubuntu1    | trusty          | source"
    echo "neutron | 1:2014.1.1-0ubuntu1.4  | trusty-security | source"
    echo "neutron | 1:2014.1.2-0ubuntu1  | trusty-proposed | source"
    echo "neutron | 1:2014.1.2-0ubuntu1  | trusty-updates  | source"
    echo "neutron | 1:2014.2~b2-0ubuntu1 | utopic          | source"

fi

if [ "$1" == "horizon" ]; then
    echo "horizon | 2012.1-0ubuntu8                            | precise          | source"
    echo "horizon | 2012.1.3+stable~20120815-691dd2-0ubuntu1.1 | precise-security | source"
    echo "horizon | 2012.1.3+stable-20130423-5ce39422-0ubuntu1 | precise-updates  | source"
    echo "horizon | 1:2014.1-0ubuntu1                          | trusty           | source"
    echo "horizon | 1:2014.1.1-0ubuntu1                        | trusty-updates   | source"
    echo "horizon | 1:2014.2~b2-0ubuntu1                       | utopic           | source"
fi

if [ "$1" == "python-neutronclient" ]; then
    echo "python-neutronclient | 1:2.3.4-0ubuntu3.2 | trusty | source, all"
    echo "python-neutronclient | 1:2.3.5-0ubuntu1 | utopic | source, all"
fi
